version: '3.8'

services:
  db:
    image: postgres:15
    container_name: docker_openupgrade-db_1
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    ports:
      - "5433:5432"
    volumes:
      - openupgrade-db-data:/var/lib/postgresql/data

  web:
    image: odoo:18
    container_name: docker_openupgrade-web_1
    depends_on:
      - db
    ports:
      - "8072:8069"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    volumes:
      - ./custom-addons:/mnt/extra-addons
    command: >
      odoo
      -d odoo18_db
      --db_host=db
      --db_port=5432
      --db_user=odoo
      --db_password=odoo
      --stop-after-init

volumes:
  openupgrade-db-data:
