version: '3'

services:
  openupgrade-db:
    container_name: docker_openupgrade-db_1
    image: postgres:15
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    ports:
      - "5433:5432"
    volumes:
      - openupgrade-db-data:/var/lib/postgresql/data

  openupgrade-web:
    container_name: docker_openupgrade-web_1
    image: odoo:18
    depends_on:
      - openupgrade-db
    environment:
      - DB_HOST=openupgrade-db
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=odoo
      - ODOO_DB=odoo18_db
    ports:
      - "8072:8069"
    volumes:
      - ./custom-addons:/mnt/extra-addons
    command: >
      odoo
      -d odoo18_db
      --db_host=openupgrade-db
      --db_port=5432
      --db_user=odoo
      --db_password=odoo
      --stop-after-init

volumes:
  openupgrade-db-data:
