version: '3.8'

services:
  openupgrade-db:
    image: postgres:15
    container_name: docker_openupgrade-db_1
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    ports:
      - "5433:5432"
    volumes:
      - openupgrade-db-data:/var/lib/postgresql/data

  openupgrade-web:
    image: odoo:18
    container_name: docker_openupgrade-web_1
    depends_on:
      - openupgrade-db
    ports:
      - "8072:8069"
    environment:
      # Odoo 18 reads these as default db params
      HOST: openupgrade-db
      USER: odoo
      PASSWORD: odoo
      DB_NAME: odoo18_db
    volumes:
      - ./custom-addons:/mnt/extra-addons
    command: >
      odoo
      -d odoo18_db
      --db_host=openupgrade-db
      --db_port=5432
      --db_user=odoo
      --db_password=odoo
      --stop-after-init

volumes:
  openupgrade-db-data:
