version: '3.8'

services:
  db:
    image: postgres:15
    container_name: odoo18-db
    environment:
      POSTGRES_DB: odoo18_db
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo18-db:/var/lib/postgresql/data

  web:
    image: odoo:18
    container_name: odoo18-web
    depends_on:
      - db
    ports:
      - "8070:8069"

    volumes:
      # âœ… OpenUpgrade addons directory (IMPORTANT)
      - ./OpenUpgrade-18.0/addons:/mnt/openupgrade_addons

    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo

volumes:
  odoo18-db:
