version: '3'

services:
  openupgrade-db:
    image: postgres:15
    container_name: openupgrade-db
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    ports:
      - "5433:5432"
    volumes:
      - openupgrade-db-data:/var/lib/postgresql/data

  openupgrade-web:
    image: odoo:18
    container_name: openupgrade-web
    depends_on:
      - openupgrade-db
    environment:
      - DB_HOST=openupgrade-db
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=odoo
    ports:
      - "8072:8069"
    volumes:
      - ./custom-addons:/mnt/extra-addons

volumes:
  openupgrade-db-data:
