version: '3'

services:
  openupgrade-db:
    container_name: docker_openupgrade-db_1
    image: postgres:15
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    ports:
      - "5433:5432"
    volumes:
      - openupgrade-db-data:/var/lib/postgresql/data

  openupgrade-web:
    container_name: docker_openupgrade-web_1
    image: odoo:18
    depends_on:
      - openupgrade-db
    environment:
      - DB_HOST=openupgrade-db
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=odoo
      - ODOO_DB=odoo18_db  # optional, helps Odoo know which DB to use
    ports:
      - "8072:8069"
    volumes:
      - ./custom-addons:/mnt/extra-addons
    command: odoo -d odoo18_db --load-language=en_US  # ensures it tries to start with the correct DB

volumes:
  openupgrade-db-data:
