version: '3.8'

services:
  db:
    image: postgres:15
    container_name: odoo18-db
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: odoo18_db
    ports:
      - "5433:5432"
    volumes:
      - odoo18-db:/var/lib/postgresql/data

  web:
    image: odoo:18
    container_name: odoo18-web
    depends_on:
      - db
    ports:
      - "8072:8069"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
      DB_NAME: odoo18_db
    volumes:
      - ./custom-addons:/mnt/extra-addons
    command: >
      odoo
      -d odoo18_db
      --db_host=db
      --db_port=5432
      --db_user=odoo
      --db_password=odoo
      --stop-after-init

volumes:
  odoo18-db:
