version: '3.8'

services:
  db:
    image: postgres:14
    container_name: odoo17-db
    environment:
      POSTGRES_DB: odoo17_db
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo17-db:/var/lib/postgresql/data

  web:
    image: odoo:17
    container_name: odoo17-web
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo

volumes:
  odoo17-db:
